config/routes.rb
DeployTest::Application.routes.draw do
  resources :posts do
    member do
      get 'email'
    end
  end
  resources :jobs
  resources :memcached do
    collection do
      get 'invalidate'
    end
  end
  resources :conversation

  resources :email_jobs
  get 'bgenvvars' => 'jobs#env_vars'

  get "home/index"

  root :to => 'home#index'

end

app/models/background_email_job.rb
class BackgroundEmailJob
  @queue = 'bg_email_queue'

  def self.perform(email_address)
    post_hash = {
      'content' => "Test background email",
      'name' => "I like email",
      'title' => "The world ain't enough",
      'email' => email_address
    }
    post = Post.new post_hash
    puts "Sending email to #{email_address}"
    UserMailer.hello_email(post).deliver
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/print_env_vars_job.rb
class PrintEnvVarsJob
  @queue = 'env_vars_queue'

  def self.perform
    puts "Environment variables"
    puts "====================="
    ENV.keys.sort {|x,y| x.upcase <=> y.upcase}.each do |key|
      puts "#{key}=#{ENV[key]}"
    end
    puts
  end
end

app/models/write_to_database_job.rb
class WriteToDatabaseJob
  @queue = 'test'

  def self.perform
    # updated to write 1GB of data each job run
    # which should take about 30 mins to run
    iterations = 1024
    posts_per_iteration = 1024
    post_byte_size = 64
    sleep_between_iterations = 1
    sleep_between_writes = 0

    puts "Job is kicking off with the following environment:"
    ENV.keys.each do |k|
      puts "#{k}=#{ENV[k]}"
    end
    puts "Creating #{posts_per_iteration} records each iteration. #{iterations} iterations. #{sleep_between_iterations} seconds sleep between each iteration. #{sleep_between_writes} second wait between each write."
    for i in 1..iterations
      puts "Iteration: #{i}/#{iterations}"
      for x in 1..posts_per_iteration
        Post.create! :content => ((0...post_byte_size).map{ ('a'..'z').to_a[rand(26)] }.join),
          :name => Socket.gethostname,
          :title => Time.now.inspect
        sleep rand * sleep_between_writes
      end
      sleep rand * sleep_between_iterations
    end
    puts "Created a total of #{Post.count} posts after #{iterations} iterations."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chat_controller.rb
class ChatController < WebsocketRails::BaseController
  include ActionView::Helpers::SanitizeHelper

  def initialize_session
    puts "Session Initialized\n"
  end
  
  def system_msg(ev, msg)
    broadcast_message ev, { 
      user_name: 'system', 
      received: Time.now.to_s(:short), 
      msg_body: msg
    }
  end
  
  def user_msg(ev, msg)
    broadcast_message ev, { 
      user_name:  connection_store[:user][:user_name], 
      received:   Time.now.to_s(:short), 
      msg_body:   ERB::Util.html_escape(msg) 
      }
  end
  
  def client_connected
    system_msg :new_message, "client #{client_id} connected"
  end
  
  def new_message
    user_msg :new_message, message[:msg_body].dup
  end
  
  def new_user
    connection_store[:user] = { user_name: sanitize(message[:user_name]) }
    broadcast_user_list
  end
  
  def change_username
    connection_store[:user][:user_name] = sanitize(message[:user_name])
    broadcast_user_list
  end
  
  def delete_user
    connection_store[:user] = nil
    system_msg "client #{client_id} disconnected"
    broadcast_user_list
  end
  
  def broadcast_user_list
    users = connection_store.collect_all(:user)
    broadcast_message :user_list, users
  end
  
end

app/controllers/conversation_controller.rb
class ConversationController < ApplicationController
  def index
  end
end

app/controllers/email_jobs_controller.rb
class EmailJobsController < ApplicationController
  def create
    email = params[:email] || "shaun@ninefold.com"
    Resque.enqueue(BackgroundEmailJob, email)
    respond_to do |format|
      format.html { redirect_to(jobs_path, notice: "Email was sent to: #{email}.") }
      format.json { render json: @jobs }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  end

  def create
    Resque.enqueue(WriteToDatabaseJob)
    redirect_to jobs_path
  end

  def env_vars
    Resque.enqueue(PrintEnvVarsJob)
    redirect_to jobs_path, notice: "Env vars printed."
  end

end

app/controllers/memcached_controller.rb
class MemcachedController < ApplicationController
  def index
    cacheme
  end

  def invalidate
    puts "Invalidating"
    Rails.cache.delete('anything-awesome')
    puts "Invalidation done"
    redirect_to memcached_index_path
  end

private
  def cacheme
    puts "Checking cache"
    Rails.cache.fetch('anything-awesome', :expires_in => 5.minute) do
        puts "not in cache"
        sleep 5
    end
    puts "End cache check"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("id desc").limit(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/email
  def email
    @post = Post.find(params[:id])

    # Tell the UserMailer to send a welcome Email after save
    success = UserMailer.hello_email(@post).deliver

    respond_to do |format|
      format.html { redirect_to(@post, notice: "Post was successfully emailed to #{@post.email}.") }
      format.json { render json: @post }
    end

  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post].permit(:name, :title, :content, :email))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post].permit(:name, :title, :content, :email))
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/conversation/index.html.erb
<h2>Websocket Chat Client</h2>

<div id="chat" class="well" data-uri="<%= request.host %>:<%= request.port %>/websocket">
</div>

<div class="form-inline well">
  <fieldset>
    <input type="text" class="input-medium" id="user_name">
    <input type="text" class="input-xlarge" id="message">
    <button id="send" class="btn btn-primary">Send</button>
  </fieldset>
</div>

app/views/home/_about.html.erb
        <p>wazza-is-awesome is a test app that was developed by an enthusiastic ruby developer. His name is wazza.</p>
        <p>The app helps us test some fundamental things about the Ninefold platform.</p>
        <p>Brutus says:</p>
        <%= image_tag "wia.png" %>

app/views/home/_apprailsconfig.html.erb
<table class="table">
  <tr><td> <b>Rails version:</b></td><td> <%= Rails.version %></td></tr>
  <th>Variable</th><th>Type</th><th>Value</th>
  <% rac = Rails.application.config -%>
  <% rac.instance_variables.sort.each do |var| %>
    <tr><td> <b><%= var %>:</b></td>
    <% value = rac.instance_variable_get(var) -%>
    <td> <%= value.class %></td><td>
    <% case value.class.to_s -%>
    <% when 'Hash' -%>
      <% value.keys.sort.each do |key| %><%= key %> => <%= value[key] %><br><% end %>
    <% when 'Array' -%>
      <% value.each do |x| %><%= x %><br><% end %>
    <% else -%>
      <%= value.inspect.scan(/.{1,20}/).join("<wbr>").html_safe %>
    <% end -%>
    </td></tr>
  <% end -%>
</table>

app/views/home/_dbconfig.html.erb
<table class="table">
    <tr><td> <b>pg_config:</b></td><td> <%= %x{pg_config} %></td></tr>
  <% Rails.application.config.database_configuration[ENV['RAILS_ENV']].each do |key,value| -%>
    <tr><td> <b><%= key %>:</b></td><td> <%= value %></td></tr>
  <% end -%>
</table>

app/views/home/_envvars.html.erb
<table class="table">
  <% ENV.keys.sort {|x,y| x.upcase <=> y.upcase}.each do |key| -%>
    <tr><td> <b><%= key %>:</b></td><td> <%= ENV[key].scan(/.{1,20}/).join("<wbr>").html_safe %></td></tr>
  <% end -%>
</table>

app/views/home/_requestheaders.html.erb
<table class="table">
    <tr><th> <b>header</b></th><th>value</th></tr>
  <% request.headers.each do |key,value| -%>
    <tr><td> <b><%= key %>:</b></td><td> <%= value %></td></tr>
  <% end -%>
</table>

app/views/home/_rubyconfig.html.erb
<table class="table">
  <% %w(Version Patchlevel Release_date Platform).each do |item| -%>
    <tr><td> <b><%= item %></b></td><td> <%= eval("RUBY_#{item.upcase}") %></td></tr>
  <% end -%>
</table>

app/views/home/index.html.erb
<h2>App Details</h2>
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Ruby configuration
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        <%= render "rubyconfig" %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          App ENV parameters
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        <%= render "envvars" %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          App Rails Config
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
        <%= render "apprailsconfig" %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
          App Database Config
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse">
      <div class="panel-body">
        <%= render "dbconfig" %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
          Request headers
        </a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse">
      <div class="panel-body">
        <%= render "requestheaders" %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
          What is this App?
        </a>
      </h4>
    </div>
    <div id="collapseSix" class="panel-collapse collapse">
      <div class="panel-body">
        <%= render "about" %>
      </div>
    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<h2>Background Jobs</h2>

<p id="notice"><%= notice %></p>

<p>There are <%= pluralize Post.count, 'post' %> in the database.</p>

<table>
<tr>
<td><%= link_to 'Create lots of posts in the background', jobs_path, :method => :post, :class => "btn" %></td>
<td>This will use Resque to create posts iteratively over time. You'll end up with lots of them.</td>
</tr>
<tr>
<td><%= link_to 'Print worker environment variables', bgenvvars_path, :method => :get, :class => "btn" %></td>
<td>Prints the list of environment variables as interpreted by the worker tier to the worker log.</td>
</tr>
<tr>
<td>Send an email</td>
<td><%= form_tag(email_jobs_path, method: :post) do %>
  <%= label_tag(:q, "Email address:") %>
  <%= text_field_tag(:email) %>
  <%= submit_tag("Email me in the background") %>
<% end %></td>
</table>

<fieldset>

</fieldset>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninefold Test App - wazza-is-awesome</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <a class="btn btn-default" href="/posts">Test the Database</a>
  <a class="btn btn-default" href="/jobs">Test Resque</a>
  <a class="btn btn-default" href="/memcached">Test Memcached</a>
  <a class="btn btn-default" href="/conversation">Test Websockets</a>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <a class="navbar-brand" href="/"><%= image_tag "logo.png" %> Ninefold Test App</a>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/posts">Database</a></li>
        <li><a href="/jobs">Resque</a></li>
        <li><a href="/memcached">Memcached</a></li>
        <li><a href="/conversation">Websockets</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </nav>

  <div id="wia-container" class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/memcached/index.html.erb
<h2>Memcached</h2>

<a class="btn btn-default" href="/memcached/invalidate">Invalidate Cache</a>

<p>Loading this page checks to see if memcached is actually working.</p>
<p>The first time it will take 5 seconds to load, the next time it will render quickly</p>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2>Editing post</h2>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h2>Listing posts</h2>

Listing the last posts from the database.

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.id %></td>
    <td><%= post.name %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= post.email %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h2>New post</h2>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<p>
  <b>Email:</b>
  <%= @post.email %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %> |
<%= link_to 'Email', email_post_path(@post) %>